# Generated by Django 4.2 on 2023-04-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="converted_to_client",
            field=models.BooleanField(default=False),
        ),
    ]
